version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_TYPE=postgresql
      - POSTGRES_SERVER=db
      - POSTGRES_USER=fdam
      - POSTGRES_PASSWORD=fdampassword
      - POSTGRES_DB=fdam
      - USE_CACHE=true
      - CACHE_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - db
      - redis
    command: >
      bash -c "python scripts/init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fdam
      - POSTGRES_PASSWORD=fdampassword
      - POSTGRES_DB=fdam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  backend_data: